### ISSUE TITLE
App crashes in Windows 7

### ISSUE THREAD

**Issue by c-sanchez** [HypsyNZ/BinanceTrader.NET#2]
I would like try BinanceTrader.NET, however the program crashes in Windows 7
![BinanceTrader.NET Windows 7 crashing](https://i.ibb.co/ykFmGwc/binacetradernet-windows7crashes.jpg)

**Comment by HypsyNZ** [comment]
Windows 7 is not supported because it is not secure.

You need a Trusted Platform Module

https://github.com/HypsyNZ/BinanceTrader.NET/wiki/Troubleshooting

**Comment by HypsyNZ** [comment]
You can download [Windows 10 - Full Strip and Lockdown Edition](https://github.com/HypsyNZ/ISOKIT) here if you don't trust Windows 10.
